### ISSUE TITLE
LoadError: UndefVarError: `@MDP_forward` not defined

### ISSUE THREAD

**Issue by zlaouar** [WhiffleFish/ConstrainedPOMDPModels#1]
https://github.com/WhiffleFish/ConstrainedPOMDPModels/blob/12c6daaab7cb74e0c387aa91872ef5ac21954548/src/gridworld.jl#L10C9-L10C9

**Comment by zlaouar** [comment]
Error when compiling

**Comment by WhiffleFish** [comment]
When checking the status of the environment, where is ConstrainedPOMDPs pointing?

**Comment by zlaouar** [comment]
ConstrainedPOMDPs v0.1.0 `https://github.com/qhho/ConstrainedPOMDPs.jl#main`

**Comment by zlaouar** [comment]
removing and adding ConstrainedPOMDPs solved the issue
